// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjOwsSZ_cjD2ul9_AypRsCywFAToCkPk8',
    appId: '1:150621159290:web:96d5bc1b5cfc0b789960c3',
    messagingSenderId: '150621159290',
    projectId: 'sdg-thesis',
    authDomain: 'sdg-thesis.firebaseapp.com',
    databaseURL: 'https://sdg-thesis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sdg-thesis.appspot.com',
    measurementId: 'G-ZYK4GS0G5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPIQiGWOfczpSceWtkKlIfwPA-Qrt5YxM',
    appId: '1:150621159290:android:a1b4c2deb09b1d569960c3',
    messagingSenderId: '150621159290',
    projectId: 'sdg-thesis',
    databaseURL: 'https://sdg-thesis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sdg-thesis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMS5sJTBgXl7XUgU-htBeOrbkuBjz76QY',
    appId: '1:150621159290:ios:3219897ceb18847b9960c3',
    messagingSenderId: '150621159290',
    projectId: 'sdg-thesis',
    databaseURL: 'https://sdg-thesis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sdg-thesis.appspot.com',
    iosBundleId: 'com.example.sdgThesis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMS5sJTBgXl7XUgU-htBeOrbkuBjz76QY',
    appId: '1:150621159290:ios:3219897ceb18847b9960c3',
    messagingSenderId: '150621159290',
    projectId: 'sdg-thesis',
    databaseURL: 'https://sdg-thesis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sdg-thesis.appspot.com',
    iosBundleId: 'com.example.sdgThesis',
  );
}
